  CREATE TABLE USERS (	
    USERID VARCHAR2(50 BYTE), 
	USERNAME VARCHAR2(50 BYTE), 
	USERPASSWORD VARCHAR2(50 BYTE), 
	USERAGE NUMBER, 
	USEREMAIL VARCHAR2(50 BYTE)
   )
   
    CREATE TABLE BOARD1 (	
    BNO NUMBER, 
	BTITLE VARCHAR2(100 BYTE), 
	BCONTENT VARCHAR2(100 BYTE), 
	BWRITER VARCHAR2(100 BYTE), 
	BDATE DATE DEFAULT SYSDATE
   )
   
   
   CREATE SEQUENCE  BNO_SEQ  MINVALUE 1 MAXVALUE 99999 INCREMENT BY 1 START WITH 49 NOCACHE  NOORDER  NOCYCLE ;